server:
  port: 3997

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'https://pintech.koreait.xyz'

        allowCredentials: true # 요청시 인증정보 전송 허가
        allowedHeaders: '*'
        allowedMethods: '*'
      discovery.locator:
        enabled: true # 유레카서버에서 찾는 여부
        lowerCaseServiceId: true # 소문자로 주소 완성
      routes:
          # member
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}

          # file
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/file/?(?<path>.*),/$\{path}

          # api
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/payment/?(?<path>.*),/$\{path}

          # ai
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/ai/?(?<path>.*),/$\{path}

          # mypage
        - id: mypage-service
          uri: lb://mypage-service
          predicates:
            - Path=/api/v1/mypage/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/mypage/?(?<path>.*),/$\{path}

          # email
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/v1/email/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/email/?(?<path>.*),/$\{path}

          # bank
        - id: bank-service
          uri: lb://bank-service
          predicates:
            - Path=/api/v1/bank/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/bank/?(?<path>.*),/$\{path}

          # board
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/board/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/board/?(?<path>.*),/$\{path}

        # loan
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/v1/loan/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/loan/?(?<path>.*),/$\{path}

        # card
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/v1/card/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/card/?(?<path>.*),/$\{path}

        # message
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/message/** # 실제 접근 경로
          filters:
            - RewritePath=/api/v1/message/?(?<path>.*),/$\{path}

# 유레카 설정
eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway